server:
  port: 8000
spring:
  messages:
    basename: i18n
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.url.host}:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  redis:
    host: ${spring.redis.host}
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100
        min-idle: 4
