server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.hlos.org:3306/hlos_mes?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: hlos_dev
    password: hlos_dev
  redis:
    host: redis.hlos.org
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100
        min-idle: 4
